import Head from 'next/head';
import { HomePage } from '../src/components/home/home-page';

export default function Home({ data }) {//le paso los datos cargados
  return (
    <div>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />{/*llamo el componente correspondiente y le paso los datos */}
    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');//para cargar los datos del json
  return {
    props: {
      data: events_categories,//cogemos solo las categorias
    },
  };
}
